name: Test & analyze Flutter codebase

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  test-and-analyze:
    name: Test & analyze Flutter codebase
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      - name: copy .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build code generated files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run Flutter Analyze
        run: flutter analyze